// ============================================================
// AUTO-GENERATED by scripts/generate_branding.py — DO NOT EDIT
// Edit config.yml and re-run the generator instead.
// ============================================================
#ifndef BRANDING_H
#define BRANDING_H

// --- Core identity ---
#define BRAND_DEVICE_NAME       "timeframe"
#define BRAND_WIFI_AP_SSID      "timeframe"

// --- URLs ---
#define BRAND_API_BASE_URL      "https://www.timeframe.app"
#define BRAND_SETUP_URL         "www.timeframe.app/start"
#define BRAND_WIFI_CONNECT_QR   "https://www.timeframe.app/start"
#define BRAND_WIFI_FAILED_QR    "https://www.timeframe.app/wifi_help"

// --- User-facing strings ---
#define BRAND_STR_WELCOME                        "Welcome to timeframe."
#define BRAND_STR_DOCK_INSTRUCTIONS              "Attach the dock and a USB-C to get started."
#define BRAND_STR_WIFI_CONNECT_SHORT             "Connect to timeframe WiFi"
#define BRAND_STR_WIFI_CONNECT_SUBTITLE          "on your phone or computer"
#define BRAND_STR_FIRMWARE_LABEL                 "timeframe firmware"
#define BRAND_STR_WIFI_CONNECT_MESSAGE           "Connect your phone or computer to the timeframe WiFi"
#define BRAND_STR_WIFI_CONNECT_QR_HELP           "or scan the QR code for help"
#define BRAND_STR_SETUP_VISIT                    "Please visit www.timeframe.app/start"
#define BRAND_STR_FRIENDLY_ID_SUFFIX             "to finish setup"
#define BRAND_STR_WIFI_FAILED                    "Can't establish WiFi connection."
#define BRAND_STR_WIFI_FAILED_HELP_BUTTON        "Hold button on the back to reset WiFi, or scan QR Code for help."
#define BRAND_STR_WIFI_FAILED_HELP_TOUCHBAR      "Hold left and right corner of touch bar to reset WiFi, or scan QR Code for help."
#define BRAND_STR_WIFI_INTERNAL_ERROR            "WiFi connected, but"
#define BRAND_STR_API_CONNECTION_FAILED_1        "API connection cannot be"
#define BRAND_STR_API_CONNECTION_FAILED_2        "established. Try to refresh,"
#define BRAND_STR_API_CONNECTION_FAILED_3        "or scan QR Code for help."
#define BRAND_STR_WIFI_WEAK                      "WiFi connected but signal is weak"
#define BRAND_STR_API_REQUEST_FAILED             "WiFi connected, request to API failed."
#define BRAND_STR_API_UNABLE_TO_CONNECT          "WiFi connected, unable connect to API."
#define BRAND_STR_API_SETUP_FAILED               "WiFi connected, /api/setup returned error."
#define BRAND_STR_API_SIZE_ERROR                 "WiFi connected, timeframe content malformed."
#define BRAND_STR_API_FIRMWARE_UPDATE_ERROR      "WiFi connected, could not get firmware update from API."
#define BRAND_STR_API_IMAGE_DOWNLOAD_ERROR       "WiFi connected, API could not deliver image to device."
#define BRAND_STR_TAP_BUTTON                     "Short click the button on back,"
#define BRAND_STR_HOLD_BUTTON_RESET              "Wait or reset by holding button on back."
#define BRAND_STR_TAP_TOUCHBAR                   "Tap the middle of touch bar,"
#define BRAND_STR_HOLD_TOUCHBAR_RESET            "Wait or reset by holding left and right corner of touch bar."
#define BRAND_STR_CHECK_INTERNET                 "otherwise check your internet."
#define BRAND_STR_WIFI_RESET_CONFIRM             "Are you sure you want to reset WiFi settings?"
#define BRAND_STR_WIFI_RESET_INSTRUCTIONS        "Hold middle of touch bar to confirm, tap to cancel."
#define BRAND_STR_POWER_OFF_CONFIRM              "Turn off device?"
#define BRAND_STR_POWER_OFF_INSTRUCTIONS         "Hold middle of touch bar to confirm, tap to cancel."
#define BRAND_STR_FW_UPDATE_AVAILABLE            "Firmware update available! Starting now..."
#define BRAND_STR_FW_UPDATE_FAILED               "Firmware update failed. Device will restart..."
#define BRAND_STR_FW_UPDATE_SUCCESS              "Firmware update success. Device will restart..."
#define BRAND_STR_WIFI_RETRY_LIMIT               "Maximum WiFi retries reached."
#define BRAND_STR_WIFI_RETRY_PRESS               "Press button to manually refresh."
#define BRAND_STR_WIFI_RETRY_HOLD                "Hold button to reset WiFi and try another network."
#define BRAND_STR_READY_TO_SHIP                  "Device is ready to ship!"
#define BRAND_STR_UNPLUG_USB                     "Unplug the USB-C to enter shipping mode."
#define BRAND_STR_PORTAL_TITLE                   "timeframe Wi-Fi Configuration"
#define BRAND_STR_PORTAL_ADVANCED_TITLE          "timeframe Advanced Configuration"
#define BRAND_STR_PORTAL_RESET_WARNING           "Are you sure? Soft resetting your timeframe device will delete all WiFi credentials, clear your Device's ID, and reset your API key."
#define BRAND_STR_PORTAL_SERVER_NOTE             "This button allows you to specify a custom API server (also known as BYOS) for your device. Most users don't want this, and will use the official server with their timeframe. Are you sure you want to have a custom server specified?"
#define BRAND_STR_PORTAL_API_PLACEHOLDER         "Enter your custom server without a trailing / (e.g. https://www.timeframe.app)"

#endif  // BRANDING_H
